"""Prompt templates."""

from .templates import (
    BINARY_PROMPT_TEMPLATE,
    NUMERIC_PROMPT_TEMPLATE,
    MULTIPLE_CHOICE_PROMPT_TEMPLATE,
    RESEARCH_SYSTEM_PROMPT,
    CLASSIFY_QUESTION_PROMPT,
    SEARCH_ENTITIES_PROMPT,
    ANALYZE_ENTITIES_PROMPT,
    SEARCH_NEWS_PROMPT,
    GENERATE_FINAL_REPORT_PROMPT,
)

__all__ = [
    "BINARY_PROMPT_TEMPLATE",
    "NUMERIC_PROMPT_TEMPLATE",
    "MULTIPLE_CHOICE_PROMPT_TEMPLATE",
    "RESEARCH_SYSTEM_PROMPT",
    "CLASSIFY_QUESTION_PROMPT",
    "SEARCH_ENTITIES_PROMPT",
    "ANALYZE_ENTITIES_PROMPT",
    "SEARCH_NEWS_PROMPT",
    "GENERATE_FINAL_REPORT_PROMPT",
]
